# frozen_string_literal: true
source "https://rubygems.org"
gem "nanoc", "~> 4.12"
gem "nanoc-webpack.rb", github: "0x1eef/nanoc-webpack.rb"
gem "ryo.rb", github: "0x1eef/ryo.rb"
gem "sass", "~> 3.7"
