#!/usr/bin/env ruby
# frozen_string_literal: true

libdir = File.expand_path File.join(__dir__, "..", "..", "lib")
require File.join(libdir, "twenty-cli")

##
# main
def main(argv)
  Twenty::Command::Console.new(argv).run
end
main(ARGV)
